//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:21:04 AM BST 
//


package com.ttdev.receta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ttdev.receta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ttdev.receta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Receta }
     * 
     */
    public Receta createReceta() {
        return new Receta();
    }

    /**
     * Create an instance of {@link Receta.FieldTipoDeTe2 .Und.Item }
     * 
     */
    public Receta.FieldTipoDeTe2 .Und.Item createRecetaFieldTipoDeTe2UndItem() {
        return new Receta.FieldTipoDeTe2 .Und.Item();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen }
     * 
     */
    public Receta.FieldImagen createRecetaFieldImagen() {
        return new Receta.FieldImagen();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen.Und }
     * 
     */
    public Receta.FieldImagen.Und createRecetaFieldImagenUnd() {
        return new Receta.FieldImagen.Und();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping }
     * 
     */
    public Receta.RdfMapping createRecetaRdfMapping() {
        return new Receta.RdfMapping();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Changed.Predicates }
     * 
     */
    public Receta.RdfMapping.Changed.Predicates createRecetaRdfMappingChangedPredicates() {
        return new Receta.RdfMapping.Changed.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Created }
     * 
     */
    public Receta.RdfMapping.Created createRecetaRdfMappingCreated() {
        return new Receta.RdfMapping.Created();
    }

    /**
     * Create an instance of {@link Receta.FieldTiempoDePreparacion.Und.Item }
     * 
     */
    public Receta.FieldTiempoDePreparacion.Und.Item createRecetaFieldTiempoDePreparacionUndItem() {
        return new Receta.FieldTiempoDePreparacion.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.CommentCount.Predicates }
     * 
     */
    public Receta.RdfMapping.CommentCount.Predicates createRecetaRdfMappingCommentCountPredicates() {
        return new Receta.RdfMapping.CommentCount.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Title }
     * 
     */
    public Receta.RdfMapping.Title createRecetaRdfMappingTitle() {
        return new Receta.RdfMapping.Title();
    }

    /**
     * Create an instance of {@link Receta.FieldTipoDeTe2 .Und }
     * 
     */
    public Receta.FieldTipoDeTe2 .Und createRecetaFieldTipoDeTe2Und() {
        return new Receta.FieldTipoDeTe2 .Und();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.CommentCount }
     * 
     */
    public Receta.RdfMapping.CommentCount createRecetaRdfMappingCommentCount() {
        return new Receta.RdfMapping.CommentCount();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Changed }
     * 
     */
    public Receta.RdfMapping.Changed createRecetaRdfMappingChanged() {
        return new Receta.RdfMapping.Changed();
    }

    /**
     * Create an instance of {@link Receta.FieldImagen.Und.Item }
     * 
     */
    public Receta.FieldImagen.Und.Item createRecetaFieldImagenUndItem() {
        return new Receta.FieldImagen.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.FieldTiempoDePreparacion.Und }
     * 
     */
    public Receta.FieldTiempoDePreparacion.Und createRecetaFieldTiempoDePreparacionUnd() {
        return new Receta.FieldTiempoDePreparacion.Und();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Rdftype }
     * 
     */
    public Receta.RdfMapping.Rdftype createRecetaRdfMappingRdftype() {
        return new Receta.RdfMapping.Rdftype();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Title.Predicates }
     * 
     */
    public Receta.RdfMapping.Title.Predicates createRecetaRdfMappingTitlePredicates() {
        return new Receta.RdfMapping.Title.Predicates();
    }

    /**
     * Create an instance of {@link Receta.Body.Und }
     * 
     */
    public Receta.Body.Und createRecetaBodyUnd() {
        return new Receta.Body.Und();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Body }
     * 
     */
    public Receta.RdfMapping.Body createRecetaRdfMappingBody() {
        return new Receta.RdfMapping.Body();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Created.Predicates }
     * 
     */
    public Receta.RdfMapping.Created.Predicates createRecetaRdfMappingCreatedPredicates() {
        return new Receta.RdfMapping.Created.Predicates();
    }

    /**
     * Create an instance of {@link Receta.Body.Und.Item }
     * 
     */
    public Receta.Body.Und.Item createRecetaBodyUndItem() {
        return new Receta.Body.Und.Item();
    }

    /**
     * Create an instance of {@link Receta.FieldTiempoDePreparacion }
     * 
     */
    public Receta.FieldTiempoDePreparacion createRecetaFieldTiempoDePreparacion() {
        return new Receta.FieldTiempoDePreparacion();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.LastActivity }
     * 
     */
    public Receta.RdfMapping.LastActivity createRecetaRdfMappingLastActivity() {
        return new Receta.RdfMapping.LastActivity();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Uid }
     * 
     */
    public Receta.RdfMapping.Uid createRecetaRdfMappingUid() {
        return new Receta.RdfMapping.Uid();
    }

    /**
     * Create an instance of {@link Receta.FieldTipoDeTe2 }
     * 
     */
    public Receta.FieldTipoDeTe2 createRecetaFieldTipoDeTe2() {
        return new Receta.FieldTipoDeTe2();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Name }
     * 
     */
    public Receta.RdfMapping.Name createRecetaRdfMappingName() {
        return new Receta.RdfMapping.Name();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Name.Predicates }
     * 
     */
    public Receta.RdfMapping.Name.Predicates createRecetaRdfMappingNamePredicates() {
        return new Receta.RdfMapping.Name.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Body.Predicates }
     * 
     */
    public Receta.RdfMapping.Body.Predicates createRecetaRdfMappingBodyPredicates() {
        return new Receta.RdfMapping.Body.Predicates();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.Uid.Predicates }
     * 
     */
    public Receta.RdfMapping.Uid.Predicates createRecetaRdfMappingUidPredicates() {
        return new Receta.RdfMapping.Uid.Predicates();
    }

    /**
     * Create an instance of {@link Receta.Body }
     * 
     */
    public Receta.Body createRecetaBody() {
        return new Receta.Body();
    }

    /**
     * Create an instance of {@link Receta.RdfMapping.LastActivity.Predicates }
     * 
     */
    public Receta.RdfMapping.LastActivity.Predicates createRecetaRdfMappingLastActivityPredicates() {
        return new Receta.RdfMapping.LastActivity.Predicates();
    }

}
