
package com.ttdev.ss;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2018-05-07T09:18:32.495+01:00
 * Generated source version: 3.0.0-milestone2
 */

@WebFault(name = "invalidProductId", targetNamespace = "http://ttdev.com/ss")
public class QueryInvalidProductId extends Exception {
    
    private com.ttdev.ss.InvalidProductId invalidProductId;

    public QueryInvalidProductId() {
        super();
    }
    
    public QueryInvalidProductId(String message) {
        super(message);
    }
    
    public QueryInvalidProductId(String message, Throwable cause) {
        super(message, cause);
    }

    public QueryInvalidProductId(String message, com.ttdev.ss.InvalidProductId invalidProductId) {
        super(message);
        this.invalidProductId = invalidProductId;
    }

    public QueryInvalidProductId(String message, com.ttdev.ss.InvalidProductId invalidProductId, Throwable cause) {
        super(message, cause);
        this.invalidProductId = invalidProductId;
    }

    public com.ttdev.ss.InvalidProductId getFaultInfo() {
        return this.invalidProductId;
    }
}
